name: alpendre
favicon: null
layout_spectrum: 0.25351
typography_spectrum: 1
title: 'alpendre  : :  ebooks  :  ideias  :  soluções  : :'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070506'
    - '#9da8bb'
    - '#244b84'
    - '#f7f6f4'
    - '#681f2a'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
